services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    whatwedo\SearchBundle\:
        resource: '../../*'

    whatwedo\SearchBundle\EventListener\IndexListener:
        tags:
            - { name: doctrine.event_subscriber, connection: default }


    whatwedo\SearchBundle\Manager\SearchableManager:
        arguments: ["whatwedo\\SearchBundle\\Discovery\\SearchableDiscovery"]
    whatwedo\SearchBundle\Discovery\SearchableDiscovery:
        arguments: ["%kernel.root_dir%", "@annotation_reader"]
