services:
    whatwedo_search.manager.index:
        class: whatwedo\SearchBundle\Manager\IndexManager
        calls:
            - method: setEntityManager
              arguments:
                  - "@doctrine.orm.entity_manager"

    whatwedo_search.event_listener.index:
        class: whatwedo\SearchBundle\EventListener\IndexListener
        arguments:
          - "@whatwedo_search.manager.index"
          - "@whatwedo_core.manager.formatter"
        tags:
            - { name: doctrine.event_subscriber, connection: default }
