services:
    whatwedo_search.manager.index:
        class: whatwedo\SearchBundle\Manager\IndexManager
        public: true
        autowire: true

    whatwedo_search.event_listener.index:
        class: whatwedo\SearchBundle\EventListener\IndexListener
        arguments:
          - "@whatwedo_search.manager.index"
          - "@whatwedo_core.manager.formatter"
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    whatwedo\SearchBundle\Command\PopulateCommand:
        tags:
            - { name: 'console.command', command: 'whatwedo:search:populate'}
